services:
  technical_task:
    build:
      context: docker/technical_task/
    ports:
      - "8000:8000"
    container_name: technical_task
    volumes:
      - ./code:/code
    env_file:
      - .env
      - example.env
    command:
       sh -c "python manage.py runservaer 0.0.0.0:8000"


    depends_on:
      - db_postgres

  db_postgres:
    image: postgres:14.6-alpine
    env_file:
      - example.env
    volumes:
      - ./docker/postgres/postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432